Create Greeter for First Launch
cpanican/capstone pull request #2
Opened 2019-10-23 15:48 UTC by ayushyamitabh

Some package requirement changes, app name fixes.

Created the Greeter for the first launch of the app, currently this only contains the UI implementation. It still has to be plugged into the server side so it can download the model from our server during the first run.

Stil need to implement the logic for only showing this window on the first run.

Let me know if there should be any additional screens. 
I will work on implementing a basic server next, that way we can starting connecting everything.

![Screen Shot 2019-10-23 at 11 45 16 AM](https://user-images.githubusercontent.com/26289557/67410859-ba377780-f58a-11e9-9138-c5e017d5212f.png)
![Screen Shot 2019-10-23 at 11 45 39 AM](https://user-images.githubusercontent.com/26289557/67410860-ba377780-f58a-11e9-866d-7f62fb665385.png)
![Screen Shot 2019-10-23 at 11 45 57 AM](https://user-images.githubusercontent.com/26289557/67410861-ba377780-f58a-11e9-8b14-d362edae2d42.png)
![Screen Shot 2019-10-23 at 11 46 03 AM](https://user-images.githubusercontent.com/26289557/67410862-ba377780-f58a-11e9-9118-7ddeddce46db.png)

2019-10-23 21:20 UTC, cpanican approved these changes
LGTM 👍

2019-10-23 21:20 UTC, cpanican commented on app/package.json
>  		"appId": "com.your-domain",
Should we change the appId too?

2019-10-23 21:26 UTC, gerryzqx requested changes
Looks pretty good to me. One thing I think would make it more readable, would be to make the fonts for the description of each screen bigger.

2019-10-24 03:37 UTC, ayushyamitabh commented
> Looks pretty good to me. One thing I think would make it more readable, would be to make the fonts for the description of each screen bigger.

Fixed - you can try to run to see other screens, this also makes sure the app runs on windows
![image](https://user-images.githubusercontent.com/26289557/67451308-05cf3d00-f5ee-11e9-8d78-f36ab84ba722.png)
![image](https://user-images.githubusercontent.com/26289557/67451317-0b2c8780-f5ee-11e9-8c12-1ba4cadda202.png)

2019-10-24 03:52 UTC, merged